export const INDIA_LOCATIONS: Record<string, string[]> = {
  "Andhra Pradesh":    ["Visakhapatnam", "Vijayawada", "Guntur", "Tirupati", "Kurnool", "Nellore", "Kadapa"],
  "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tezpur"],
  "Assam":             ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tezpur"],
  "Bihar":             ["Patna", "Gaya", "Muzaffarpur", "Bhagalpur", "Darbhanga", "Purnia", "Ara"],
  "Chhattisgarh":      ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg", "Rajnandgaon"],
  "Delhi":             ["New Delhi", "North Delhi", "South Delhi", "East Delhi", "West Delhi", "Dwarka", "Rohini"],
  "Goa":               ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"],
  "Gujarat":           ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Anand"],
  "Haryana":           ["Faridabad", "Gurgaon", "Panipat", "Ambala", "Hisar", "Karnal", "Rohtak", "Yamunanagar"],
  "Himachal Pradesh":  ["Shimla", "Dharamsala", "Solan", "Mandi", "Kullu", "Manali", "Palampur"],
  "Jharkhand":         ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar", "Hazaribagh"],
  "Karnataka":         ["Bengaluru", "Mysuru", "Hubli", "Mangaluru", "Belagavi", "Dharwad", "Kalaburagi", "Tumkur"],
  "Kerala":            ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Palakkad", "Alappuzha"],
  "Madhya Pradesh":    ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Rewa", "Satna"],
  "Maharashtra":       ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Kolhapur", "Solapur", "Amravati", "Nanded"],
  "Manipur":           ["Imphal", "Thoubal", "Bishnupur", "Churachandpur", "Ukhrul"],
  "Meghalaya":         ["Shillong", "Tura", "Jowai", "Nongpoh"],
  "Mizoram":           ["Aizawl", "Lunglei", "Saiha", "Champhai"],
  "Nagaland":          ["Kohima", "Dimapur", "Mokokchung", "Wokha"],
  "Odisha":            ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri"],
  "Punjab":            ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Hoshiarpur"],
  "Rajasthan":         ["Jaipur", "Jodhpur", "Udaipur", "Ajmer", "Kota", "Bikaner", "Alwar", "Bharatpur"],
  "Sikkim":            ["Gangtok", "Namchi", "Mangan", "Gyalshing"],
  "Tamil Nadu":        ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Vellore", "Erode"],
  "Telangana":         ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Nalgonda"],
  "Tripura":           ["Agartala", "Udaipur", "Dharmanagar", "Kailasahar"],
  "Uttar Pradesh":     ["Lucknow", "Varanasi", "Agra", "Kanpur", "Meerut", "Allahabad", "Gorakhpur", "Ghaziabad", "Noida"],
  "Uttarakhand":       ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rishikesh", "Nainital", "Mussoorie"],
  "West Bengal":       ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Darjeeling", "Malda"],
};

export const INDIA_STATES = Object.keys(INDIA_LOCATIONS).sort();
